DEV_SEED_YEAR = 2026

DEV_FINALISTS = [
    {"running_order": 1, "country_name": "Denmark", "country_code": "DK", "artist_name": "Søren Torpegaard Lund", "song_title": "Før Vi Går Hjem"},
    {"running_order": 2, "country_name": "Germany", "country_code": "DE", "artist_name": "Sarah Engels", "song_title": "Fire"},
    {"running_order": 3, "country_name": "Israel", "country_code": "IL", "artist_name": "Noam Bettan", "song_title": "Michelle"},
    {"running_order": 4, "country_name": "Belgium", "country_code": "BE", "artist_name": "ESSYLA", "song_title": "Dancing on the Ice"},
    {"running_order": 5, "country_name": "Albania", "country_code": "AL", "artist_name": "Alis", "song_title": "Nân"},
    {"running_order": 6, "country_name": "Greece", "country_code": "GR", "artist_name": "Akylas", "song_title": "Ferto"},
    {"running_order": 7, "country_name": "Ukraine", "country_code": "UA", "artist_name": "LELÉKA", "song_title": "Ridnym", "is_ukraine": True},
    {"running_order": 8, "country_name": "Australia", "country_code": "AU", "artist_name": "Delta Goodrem", "song_title": "Eclipse"},
    {"running_order": 9, "country_name": "Serbia", "country_code": "RS", "artist_name": "LAVINA", "song_title": "Kraj Mene"},
    {"running_order": 10, "country_name": "Malta", "country_code": "MT", "artist_name": "AIDAN", "song_title": "Bella"},
    {"running_order": 11, "country_name": "Czechia", "country_code": "CZ", "artist_name": "Daniel Zizka", "song_title": "CROSSROADS"},
    {"running_order": 12, "country_name": "Bulgaria", "country_code": "BG", "artist_name": "DARA", "song_title": "Bangaranga"},
    {"running_order": 13, "country_name": "Croatia", "country_code": "HR", "artist_name": "LELEK", "song_title": "Andromeda"},
    {"running_order": 14, "country_name": "United Kingdom", "country_code": "GB", "artist_name": "LOOK MUM NO COMPUTER", "song_title": "Eins, Zwei, Drei"},
    {"running_order": 15, "country_name": "France", "country_code": "FR", "artist_name": "Monroe", "song_title": "Regarde !"},
    {"running_order": 16, "country_name": "Moldova", "country_code": "MD", "artist_name": "Satoshi", "song_title": "Viva, Moldova!"},
    {"running_order": 17, "country_name": "Finland", "country_code": "FI", "artist_name": "Linda Lampenius x Pete Parkkonen", "song_title": "Liekinheitin"},
    {"running_order": 18, "country_name": "Poland", "country_code": "PL", "artist_name": "ALICJA", "song_title": "Pray"},
    {"running_order": 19, "country_name": "Lithuania", "country_code": "LT", "artist_name": "Lion Ceccah", "song_title": "Sólo Quiero Más"},
    {"running_order": 20, "country_name": "Sweden", "country_code": "SE", "artist_name": "FELICIA", "song_title": "My System"},
    {"running_order": 21, "country_name": "Cyprus", "country_code": "CY", "artist_name": "Antigoni", "song_title": "JALLA"},
    {"running_order": 22, "country_name": "Italy", "country_code": "IT", "artist_name": "Sal Da Vinci", "song_title": "Per Sempre Sì"},
    {"running_order": 23, "country_name": "Norway", "country_code": "NO", "artist_name": "JONAS LOVV", "song_title": "YA YA YA"},
    {"running_order": 24, "country_name": "Romania", "country_code": "RO", "artist_name": "Alexandra Căpitănescu", "song_title": "Choke Me"},
    {"running_order": 25, "country_name": "Austria", "country_code": "AT", "artist_name": "COSMÓ", "song_title": "Tanzschein"},
]
