# Generated by Django 5.2.14 on 2026-05-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContestEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('state', models.CharField(choices=[('setup', 'Setup'), ('voting_open', 'Voting open'), ('voting_closed', 'Voting closed'), ('official_results_entered', 'Official results entered'), ('scores_published', 'Scores published')], default='setup', max_length=32)),
                ('voting_open_at', models.DateTimeField(blank=True, null=True)),
                ('voting_closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ContestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running_order', models.PositiveSmallIntegerField()),
                ('country_name', models.CharField(max_length=120)),
                ('country_code', models.CharField(max_length=3)),
                ('artist_name', models.CharField(max_length=160)),
                ('song_title', models.CharField(max_length=160)),
                ('is_ukraine', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='contest.contestedition')),
            ],
            options={
                'ordering': ['edition__year', 'running_order'],
                'constraints': [models.UniqueConstraint(fields=('edition', 'running_order'), name='unique_running_order_per_edition'), models.UniqueConstraint(condition=models.Q(('is_ukraine', True)), fields=('edition',), name='unique_ukraine_entry_per_edition')],
            },
        ),
    ]
