# Generated by Django 5.2.14 on 2026-05-13 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_rank', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_results', to='contest.contestentry')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_results', to='contest.contestedition')),
            ],
            options={
                'ordering': ['final_rank'],
                'constraints': [models.UniqueConstraint(fields=('edition', 'final_rank'), name='unique_official_rank_per_edition'), models.UniqueConstraint(fields=('edition', 'contest_entry'), name='unique_official_entry_per_edition')],
            },
        ),
    ]
