# Generated by Django 5.2.14 on 2026-05-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_officialresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialresult',
            name='jury_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialresult',
            name='televote_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officialresult',
            name='total_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
