# Generated by Django 5.2.14 on 2026-05-13 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('with_ukraine', 'With Ukraine'), ('without_ukraine', 'Without Ukraine')], max_length=32)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('immutable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='contest.contestedition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BallotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField()),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='voting.ballot')),
                ('contest_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballot_items', to='contest.contestentry')),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.UniqueConstraint(fields=('edition', 'user', 'mode'), name='unique_ballot_per_user_mode'),
        ),
        migrations.AddConstraint(
            model_name='ballotitem',
            constraint=models.UniqueConstraint(fields=('ballot', 'points'), name='unique_points_per_ballot'),
        ),
        migrations.AddConstraint(
            model_name='ballotitem',
            constraint=models.UniqueConstraint(fields=('ballot', 'contest_entry'), name='unique_entry_per_ballot'),
        ),
        migrations.AddConstraint(
            model_name='ballotitem',
            constraint=models.CheckConstraint(condition=models.Q(('points__in', (1, 2, 3, 4, 5, 6, 7, 8, 10, 12))), name='ballot_item_allowed_points'),
        ),
    ]
