# Generated by Django 5.2.14 on 2026-05-13 13:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_officialresult'),
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('with_ukraine', 'With Ukraine'), ('without_ukraine', 'Without Ukraine')], max_length=32)),
                ('exact_hits', models.PositiveSmallIntegerField(default=0)),
                ('top10_hits_wrong_place', models.PositiveSmallIntegerField(default=0)),
                ('total_score', models.PositiveSmallIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='contest.contestedition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_score', '-exact_hits', '-top10_hits_wrong_place', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('edition', 'user', 'mode'), name='unique_user_score_per_mode')],
            },
        ),
    ]
