# Generated by Django 5.2.14 on 2026-05-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_userscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='immutable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
